config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root "home#welcome"
  resources :genres, only: :index do
    member do
      get "movies"
    end
  end
  resources :movies, only: [:index, :show] do
    member do
      get :send_info
    end
    collection do
      get :export
    end
    resources :comments, only: [:create, :destroy, :show]
  end
  resources :comments, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :movie

  scope :last_week, -> { where("created_at >= :date", :date => 1.week.ago) } 
end

app/models/concerns/title_brackets_validator.rb
class TitleBracketsValidator < ActiveModel::Validator
  def validate(title)
    def valid_string?(title)
      strim = title.gsub(/[^\[\]\(\)\{\}]/,'')
      return true if strim.empty?
      return false if strim.size.odd?
      loop do  
        s = strim.gsub('()','').gsub('[]','').gsub('{}','')
        return true if s.empty?
        return false if s == strim
        strim = s
      end   
    end
  end
end

app/models/genre.rb
# == Schema Information
#
# Table name: genres
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime
#  updated_at :datetime
#

class Genre < ApplicationRecord
  has_many :movies
end

app/models/movie.rb
# == Schema Information
#
# Table name: movies
#
#  id          :integer          not null, primary key
#  title       :string
#  description :text
#  released_at :datetime
#  avatar      :string
#  genre_id    :integer
#  created_at  :datetime
#  updated_at  :datetime
#

class Movie < ApplicationRecord
  belongs_to :genre
  has_many :comments, dependent: :destroy

  validates_with TitleBracketsValidator
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default("0"), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  created_at             :datetime
#  updated_at             :datetime
#

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  validates :phone_number, format: { with: /\A[+]?\d+(?>[- .]\d+)*\z/, allow_nil: true }
  has_many :comments

  scope :last_week_comments, -> { where("created_at >= :date", :date => 1.week.ago) } 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    added_attrs = [:name, :email, :password, :password_confirmation]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_movie, only: [:create, :destroy]
  before_action :set_comments, only: [:show]

  expose(:comment)
  
  def new
  	@comment = Comment.new(comments_params)
  	@comment.user_id = current_user.id
  	@comment.movie_id = @movie.id
  end

  def create
  	@movie = Movie.find(params[:movie_id])
  	@comment = @movie.comments.create(comments_params)
  	@comment.user_id = current_user.id
  	@comment.movie_id = @movie.id

  	if @comment.save
  		redirect_to @movie
  		flash.now[:succes] = "hurra"
  	else
  		redirect_to @movie
  		flash.now[:error] = "error"
  	end
  end

  def index
    @commenters = Comment.last_week.group(:user_id).count.sort_by {|k,v| v}.reverse.to_h
  end
  
  def edit  	
  end

  def update  	
  end

  def destroy
    @comment = Comment.find(params[:id])
    
    if current_user.id == @comment.user_id
      @comment.destroy
    else
      flash.now[:error] = "You can't do that!"
    end
    
    respond_to do |format|
      format.html { redirect_to movie_path(@movie) }
      format.xml  { head :ok }
    end
  end
  private
  
    def set_comments
      @comments = Comment.where(movie_id: :movie_id)
    end

    def set_movie
  	 @movie = Movie.find(params[:movie_id])
    end

    def comments_params
      params.require(:comment).permit(:title, :body, :author, :user_id, :movie_id)
    end
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  expose_decorated(:genres) { Genre.all }
  expose_decorated(:genre)
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def welcome; end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :authenticate_user!, only: [:send_info, :show]

  expose_decorated(:movies) { Movie.all }
  expose(:movie)

  def send_info
    MovieInfoMailer.send_info(current_user, movie).deliver_now
    redirect_to :back, notice: "Email sent with movie info"
  end

  def show
    @movie = Movie.find(params[:id])
    @comments = @movie.comments
  end

  def export
    file_path = "tmp/movies.csv"
    MovieExporter.new.call(current_user, file_path)
    redirect_to root_path, notice: "Movies exported"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.haml
.container.comments
  %h3 Comment:
  %p
    %strong Commenter:
    = comment.author
  %p
    %strong Title
    = comment.title
  %p
    %strong Content
    = comment.body
  %p
    -if current_user.id == comment.user_id
      = link_to 'Delete Comment', 
                            movie_comment_path(@movie, comment), 
                            method: :delete,
                            data: { confirm: 'Are you sure?' }
  %hr.comments

app/views/comments/_form.html.haml
= bootstrap_form_for [@movie, @movie.comments.build], url: movie_comments_path(@movie), html: { multipart: true }, layout: :horizontal  do |f|
  = f.text_field :title, :placeholder => 'Title'
  = f.text_area :body, placeholder: 'Body'
  = f.hidden_field :user_id, :value => current_user.id
  = f.hidden_field :author, :value => current_user.try(:name).try(:id)
  = f.hidden_field :movie_id, :value => @movie.id
  = f.submit 'Zapisz zmiany', class: 'btn btn-primary col-sm-offset-3'

app/views/comments/_new.html.haml
- if @movie.comments.where(user_id: current_user.id).exists?
- else
  %h2 Add Comment:
  %br= render 'comments/form'

app/views/comments/index.html.haml
.container
  .row
    .col-md-6
      %h1 TOP 10 COMMENTERS
      %ul.commenters
        - @commenters.first(10).each do |id, count|
          %li= "User_#{id} wrote " + pluralize( count, "comment" )

          

app/views/genres/index.html.haml
.row
  .col-md-8.col-md-offset-2.col-lg-8.col-lg-offset-2
    %h1.text-center All genres
    %table.table.table-striped
      %thead
        %tr
          %th #
          %th Name
          %th Number of movies
          %th Created at
      %tbody
        - genres.each_with_index do |genre, i|
          %tr
            %td= i + 1
            %td= genre.name
            %td= genre.number_of_movies
            %td= genre.created_at

app/views/genres/movies.html.haml
.row
  .col-md-8.col-md-offset-2.col-lg-8.col-lg-offset-2
    %h1.text-center
      Movies by genre:
      = genre.name
    = render 'movies/movies_table', movies: genre.movies 

app/views/home/welcome.html.haml
.row
  .col-md-8.col-md-offset-2.col-lg-8.col-lg-offset-2
    %h1.text-center Welcome to Pairguru App!
    %p.lead.text-center Place where we examine our candidates

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
%nav.navbar.navbar-default.navbar-static-top
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to 'Pairguru App', root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      %ul.nav.navbar-nav
        = render 'layouts/navigation_links'
      %ul.nav.navbar-nav.navbar-right
        = render 'layouts/navigation_links_right'

app/views/layouts/_navigation_links.html.haml
%li= link_to 'Movies', movies_path
%li= link_to 'Genres', genres_path
- if user_signed_in?
  %li= link_to 'Export', export_movies_path

app/views/layouts/_navigation_links_right.html.haml
- if user_signed_in?
  %li= link_to 'Logout', destroy_user_session_path, method: :delete
- else
  %li= link_to 'Login', new_user_session_path
  %li= link_to 'Register', new_user_registration_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{ name: "viewport", content: "width=device-width, initial-scale=1.0" }
    %title= content_for?(:title) ? yield(:title) : 'Pairguru'
    %meta{ name: "description", content: "#{content_for?(:description) ? yield(:description) : 'Props'}" }
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body
    #announcements-region
    %header
      #header-region
        = render 'layouts/navigation'
    %main
      .container
        #main-region
        = render 'layouts/messages'
        = yield
    %footer.text-center
      Magic by
      = link_to 'netguru', 'https://netguru.co'

app/views/movies/_movies_table.html.haml
%table.table.table-striped
  %tbody
    - movies.each_with_index do |movie, i|
      %tr
        %td= i + 1
        %td
          %img.img-rounded{ src: movie.cover }
        %td
          %h4
            = link_to movie.title, movie_path(movie)
          %p
            %strong
              =link_to movie.genre.name, movies_genre_path(movie.genre)
            = ' (' + movie.released_at.to_s + ')'
          %p= movie.description

app/views/movies/index.html.haml
.row
  .col-md-8.col-md-offset-2.col-lg-8.col-lg-offset-2
    %h1.text-center Movies
    = render 'movies_table', movies: movies

app/views/movies/show.html.haml
%h1= movie.title
.jumbotron
  = movie.description
- if user_signed_in?
  %p= link_to 'Email me details about this movie', send_info_movie_path(movie), class: 'btn btn-sm btn-default'
  .container.comments  
    .row.col-md-3.col-md-6
      = render 'comments/new'
      = render @comments